### ISSUE TITLE
Sidebar meny is scrolable

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#208]
**Firefox:**
<img width="1280" alt="Screenshot 2023-11-07 at 09 12 55" src="https://github.com/beda-software/fhir-emr/assets/1488983/d1ea9292-a0f3-468a-bd2b-81696d824dd6">
**Chome:**
<img width="1280" alt="Screenshot 2023-11-07 at 09 19 57" src="https://github.com/beda-software/fhir-emr/assets/1488983/fca024db-7e45-4f2b-992c-4ffc85f3a877">

**Comment by projkov** [comment]
This issue is fixed. Changes are delivered to the production environment.

**Comment by ir4y** [comment]
@projkov vertical scroll still present

![Image](https://github.com/beda-software/fhir-emr/assets/1488983/4860f206-f1fe-414f-a2e5-9290a190fab5)
